# Blueprint metadata
blueprint:
  name: deCONZ - Livarno Lux 4-Button Remote
  description: deCONZ automation for executing any kind of action triggered by the provided Livarno Lux Wireless 4-Button Remote.
  source_url: https://github.com/Ediste/ha-blueprints/livarno-lux-dimming-remote.yml
  domain: automation
  input:
    remote:
      name: Remote
      description: The device to use for the automation.
      selector:
        device:
          integration: deconz
          manufacturer: LIDL Livarno Lux

    action_button_one:
      name: (Optional) first button press
      description: Action to run on first button press.
      default: []
      selector:
        action: {}

    action_button_two:
      name: (Optional) second button press
      description: Action to run on second button press.
      default: []
      selector:
        action: {}

    action_button_three:
      name: (Optional) third button press
      description: Action to run on third button press.
      default: []
      selector:
        action: {}

    action_button_four:
      name: (Optional) fourth button press
      description: Action to run on fourth button press.
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent
trigger:
  # trigger for other integrations
  - platform: event
    event_type: deconz_event
    event_data:
      device_id: !input remote
action:
  - variables:
      event: "{{ trigger.event.data.event }}"
  - choose:
      - conditions: "{{ event == 4002 }}"
        sequence: !input action_button_one
      - conditions: "{{ event == 1002 }}"
        sequence: !input action_button_two
      - conditions: "{{ event == 2002 }}"
        sequence: !input action_button_three
      - conditions: "{{ event == 3002 }}"
        sequence: !input action_button_four
